RANDOM=1

/**
 * Display the pixel of one bloc
 * HL=screen, DE=logo
 */

 macro MACRO_DISPLAY_PIXEL_OF_BLOC X, Y
X_DELTA=(X/4)
X_PIXEL=(X%4)

 if Y>0
    ;; Screen Y movt
    ld a, h
    dup Y
        add 0x08
    edup
    ld h, a
 endif

    ;; Screen X movt
 if X_DELTA>0
    dup X_DELTA
        inc hl
    edup
 endif

    ; Get logo source
    ld a, h
    sub 0x40
    ld d, a
    ld e, l

    ;; Get pixel mask (1 for pixel, 0 for others)
    ld bc, PIXEL_MASK + X_PIXEL
    ld a, (bc) : ld c, a

  ld b, DISPLAYED_LOGO_WIDTH ; LOGO_WIDTH
1
    ;; Merge with logo value
    ld a, (de) 
    and c

    ;; Display on screen
    or (hl)
    ld (hl), a

   .2 inc hl
   .2 inc de
   djnz 1b
    ret
 endm


/**
 * Reference to routines
 */
DISPLAY_BLOC_TABLE
 if RANDOM
	dw BLOC_DISPLAY_ROUTINES_PIX18    
	dw BLOC_DISPLAY_ROUTINES_PIX8    
	dw BLOC_DISPLAY_ROUTINES_PIX62    
	dw BLOC_DISPLAY_ROUTINES_PIX5    
	dw BLOC_DISPLAY_ROUTINES_PIX56    
	dw BLOC_DISPLAY_ROUTINES_PIX41    
	dw BLOC_DISPLAY_ROUTINES_PIX11    
	dw BLOC_DISPLAY_ROUTINES_PIX22    
	dw BLOC_DISPLAY_ROUTINES_PIX34    
	dw BLOC_DISPLAY_ROUTINES_PIX50    
	dw BLOC_DISPLAY_ROUTINES_PIX49    
	dw BLOC_DISPLAY_ROUTINES_PIX38    
	dw BLOC_DISPLAY_ROUTINES_PIX23    
	dw BLOC_DISPLAY_ROUTINES_PIX17    
	dw BLOC_DISPLAY_ROUTINES_PIX42    
	dw BLOC_DISPLAY_ROUTINES_PIX13    
	dw BLOC_DISPLAY_ROUTINES_PIX28    
	dw BLOC_DISPLAY_ROUTINES_PIX57    
	dw BLOC_DISPLAY_ROUTINES_PIX33    
	dw BLOC_DISPLAY_ROUTINES_PIX16    
	dw BLOC_DISPLAY_ROUTINES_PIX51    
	
	
	dw BLOC_DISPLAY_ROUTINES_PIX63    
	dw BLOC_DISPLAY_ROUTINES_PIX1    
	dw BLOC_DISPLAY_ROUTINES_PIX25    
	dw BLOC_DISPLAY_ROUTINES_PIX32    
	dw BLOC_DISPLAY_ROUTINES_PIX10    
	dw BLOC_DISPLAY_ROUTINES_PIX30    
	dw BLOC_DISPLAY_ROUTINES_PIX43    
	dw BLOC_DISPLAY_ROUTINES_PIX27    
	dw BLOC_DISPLAY_ROUTINES_PIX61    
	dw BLOC_DISPLAY_ROUTINES_PIX58    
	dw BLOC_DISPLAY_ROUTINES_PIX54    
	dw BLOC_DISPLAY_ROUTINES_PIX24    
	dw BLOC_DISPLAY_ROUTINES_PIX31    
	dw BLOC_DISPLAY_ROUTINES_PIX7    
	dw BLOC_DISPLAY_ROUTINES_PIX26    
	dw BLOC_DISPLAY_ROUTINES_PIX39    
	dw BLOC_DISPLAY_ROUTINES_PIX37    
	dw BLOC_DISPLAY_ROUTINES_PIX47    







	dw BLOC_DISPLAY_ROUTINES_PIX35    
	dw BLOC_DISPLAY_ROUTINES_PIX21    
	dw BLOC_DISPLAY_ROUTINES_PIX14    
	dw BLOC_DISPLAY_ROUTINES_PIX19    
	dw BLOC_DISPLAY_ROUTINES_PIX9    
	dw BLOC_DISPLAY_ROUTINES_PIX3    
	dw BLOC_DISPLAY_ROUTINES_PIX52    
	dw BLOC_DISPLAY_ROUTINES_PIX36    
	dw BLOC_DISPLAY_ROUTINES_PIX20    
	dw BLOC_DISPLAY_ROUTINES_PIX40    
	dw BLOC_DISPLAY_ROUTINES_PIX6    
	dw BLOC_DISPLAY_ROUTINES_PIX55    
	dw BLOC_DISPLAY_ROUTINES_PIX44    
	dw BLOC_DISPLAY_ROUTINES_PIX12    
	dw BLOC_DISPLAY_ROUTINES_PIX0    
	dw BLOC_DISPLAY_ROUTINES_PIX45    
	dw BLOC_DISPLAY_ROUTINES_PIX60    
	dw BLOC_DISPLAY_ROUTINES_PIX29    
	dw BLOC_DISPLAY_ROUTINES_PIX53    
	dw BLOC_DISPLAY_ROUTINES_PIX46    
	dw BLOC_DISPLAY_ROUTINES_PIX59    
	dw BLOC_DISPLAY_ROUTINES_PIX48    
	dw BLOC_DISPLAY_ROUTINES_PIX2    
	dw BLOC_DISPLAY_ROUTINES_PIX4    
	dw BLOC_DISPLAY_ROUTINES_PIX15    


 else
	dw BLOC_DISPLAY_ROUTINES_PIX0    
	dw BLOC_DISPLAY_ROUTINES_PIX1    
	dw BLOC_DISPLAY_ROUTINES_PIX2    
	dw BLOC_DISPLAY_ROUTINES_PIX3    
	dw BLOC_DISPLAY_ROUTINES_PIX4    
	dw BLOC_DISPLAY_ROUTINES_PIX5    
	dw BLOC_DISPLAY_ROUTINES_PIX6    
	dw BLOC_DISPLAY_ROUTINES_PIX7    

	dw BLOC_DISPLAY_ROUTINES_PIX8    
	dw BLOC_DISPLAY_ROUTINES_PIX9    
	dw BLOC_DISPLAY_ROUTINES_PIX10    
	dw BLOC_DISPLAY_ROUTINES_PIX11    
	dw BLOC_DISPLAY_ROUTINES_PIX12    
	dw BLOC_DISPLAY_ROUTINES_PIX13    
	dw BLOC_DISPLAY_ROUTINES_PIX14    
	dw BLOC_DISPLAY_ROUTINES_PIX15    

	dw BLOC_DISPLAY_ROUTINES_PIX16    
	dw BLOC_DISPLAY_ROUTINES_PIX17    
	dw BLOC_DISPLAY_ROUTINES_PIX18    
	dw BLOC_DISPLAY_ROUTINES_PIX19    
	dw BLOC_DISPLAY_ROUTINES_PIX20    
	dw BLOC_DISPLAY_ROUTINES_PIX21    
	dw BLOC_DISPLAY_ROUTINES_PIX22    
	dw BLOC_DISPLAY_ROUTINES_PIX23    

	dw BLOC_DISPLAY_ROUTINES_PIX24    
	dw BLOC_DISPLAY_ROUTINES_PIX25    
	dw BLOC_DISPLAY_ROUTINES_PIX26    
	dw BLOC_DISPLAY_ROUTINES_PIX27    
	dw BLOC_DISPLAY_ROUTINES_PIX28    
	dw BLOC_DISPLAY_ROUTINES_PIX29    
	dw BLOC_DISPLAY_ROUTINES_PIX30    
	dw BLOC_DISPLAY_ROUTINES_PIX31    

	dw BLOC_DISPLAY_ROUTINES_PIX32    
	dw BLOC_DISPLAY_ROUTINES_PIX33    
	dw BLOC_DISPLAY_ROUTINES_PIX34    
	dw BLOC_DISPLAY_ROUTINES_PIX35    
	dw BLOC_DISPLAY_ROUTINES_PIX36    
	dw BLOC_DISPLAY_ROUTINES_PIX37    
	dw BLOC_DISPLAY_ROUTINES_PIX38    
	dw BLOC_DISPLAY_ROUTINES_PIX39    

	dw BLOC_DISPLAY_ROUTINES_PIX40    
	dw BLOC_DISPLAY_ROUTINES_PIX41    
	dw BLOC_DISPLAY_ROUTINES_PIX42    
	dw BLOC_DISPLAY_ROUTINES_PIX43    
	dw BLOC_DISPLAY_ROUTINES_PIX44    
	dw BLOC_DISPLAY_ROUTINES_PIX45    
	dw BLOC_DISPLAY_ROUTINES_PIX46    
	dw BLOC_DISPLAY_ROUTINES_PIX47    
	
	dw BLOC_DISPLAY_ROUTINES_PIX48    
	dw BLOC_DISPLAY_ROUTINES_PIX49    
	dw BLOC_DISPLAY_ROUTINES_PIX50    
	dw BLOC_DISPLAY_ROUTINES_PIX51    
	dw BLOC_DISPLAY_ROUTINES_PIX52    
	dw BLOC_DISPLAY_ROUTINES_PIX53    
	dw BLOC_DISPLAY_ROUTINES_PIX54    
	dw BLOC_DISPLAY_ROUTINES_PIX55    
	
	dw BLOC_DISPLAY_ROUTINES_PIX56    
	dw BLOC_DISPLAY_ROUTINES_PIX57    
	dw BLOC_DISPLAY_ROUTINES_PIX58    
	dw BLOC_DISPLAY_ROUTINES_PIX59    
	dw BLOC_DISPLAY_ROUTINES_PIX60    
	dw BLOC_DISPLAY_ROUTINES_PIX61    
	dw BLOC_DISPLAY_ROUTINES_PIX62    
	dw BLOC_DISPLAY_ROUTINES_PIX63    
 endif

/**
 * List of real routines
 */
BLOC_DISPLAY_ROUTINES_PIX0    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 0
BLOC_DISPLAY_ROUTINES_PIX1    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 1
BLOC_DISPLAY_ROUTINES_PIX2    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 2
BLOC_DISPLAY_ROUTINES_PIX3    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 3
BLOC_DISPLAY_ROUTINES_PIX4    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 4
BLOC_DISPLAY_ROUTINES_PIX5    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 5
BLOC_DISPLAY_ROUTINES_PIX6    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 6
BLOC_DISPLAY_ROUTINES_PIX7    MACRO_DISPLAY_PIXEL_OF_BLOC 0, 7
 
BLOC_DISPLAY_ROUTINES_PIX8    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 0
BLOC_DISPLAY_ROUTINES_PIX9    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 1
BLOC_DISPLAY_ROUTINES_PIX10    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 2
BLOC_DISPLAY_ROUTINES_PIX11    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 3
BLOC_DISPLAY_ROUTINES_PIX12    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 4
BLOC_DISPLAY_ROUTINES_PIX13    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 5
BLOC_DISPLAY_ROUTINES_PIX14    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 6
BLOC_DISPLAY_ROUTINES_PIX15    MACRO_DISPLAY_PIXEL_OF_BLOC 1, 7

BLOC_DISPLAY_ROUTINES_PIX16    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 0
BLOC_DISPLAY_ROUTINES_PIX17    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 1
BLOC_DISPLAY_ROUTINES_PIX18    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 2
BLOC_DISPLAY_ROUTINES_PIX19    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 3
BLOC_DISPLAY_ROUTINES_PIX20    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 4
BLOC_DISPLAY_ROUTINES_PIX21    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 5
BLOC_DISPLAY_ROUTINES_PIX22    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 6
BLOC_DISPLAY_ROUTINES_PIX23    MACRO_DISPLAY_PIXEL_OF_BLOC 2, 7

BLOC_DISPLAY_ROUTINES_PIX24    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 0
BLOC_DISPLAY_ROUTINES_PIX25    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 1
BLOC_DISPLAY_ROUTINES_PIX26    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 2
BLOC_DISPLAY_ROUTINES_PIX27    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 3
BLOC_DISPLAY_ROUTINES_PIX28    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 4
BLOC_DISPLAY_ROUTINES_PIX29    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 5
BLOC_DISPLAY_ROUTINES_PIX30    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 6
BLOC_DISPLAY_ROUTINES_PIX31    MACRO_DISPLAY_PIXEL_OF_BLOC 3, 7

BLOC_DISPLAY_ROUTINES_PIX32    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 0
BLOC_DISPLAY_ROUTINES_PIX33    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 1
BLOC_DISPLAY_ROUTINES_PIX34    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 2
BLOC_DISPLAY_ROUTINES_PIX35    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 3
BLOC_DISPLAY_ROUTINES_PIX36    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 4
BLOC_DISPLAY_ROUTINES_PIX37    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 5
BLOC_DISPLAY_ROUTINES_PIX38    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 6
BLOC_DISPLAY_ROUTINES_PIX39    MACRO_DISPLAY_PIXEL_OF_BLOC 4, 7

BLOC_DISPLAY_ROUTINES_PIX40    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 0
BLOC_DISPLAY_ROUTINES_PIX41    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 1
BLOC_DISPLAY_ROUTINES_PIX42    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 2
BLOC_DISPLAY_ROUTINES_PIX43    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 3
BLOC_DISPLAY_ROUTINES_PIX44    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 4
BLOC_DISPLAY_ROUTINES_PIX45    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 5
BLOC_DISPLAY_ROUTINES_PIX46    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 6
BLOC_DISPLAY_ROUTINES_PIX47    MACRO_DISPLAY_PIXEL_OF_BLOC 5, 7

BLOC_DISPLAY_ROUTINES_PIX48    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 0
BLOC_DISPLAY_ROUTINES_PIX49    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 1
BLOC_DISPLAY_ROUTINES_PIX50    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 2
BLOC_DISPLAY_ROUTINES_PIX51    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 3
BLOC_DISPLAY_ROUTINES_PIX52    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 4
BLOC_DISPLAY_ROUTINES_PIX53    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 5
BLOC_DISPLAY_ROUTINES_PIX54    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 6
BLOC_DISPLAY_ROUTINES_PIX55    MACRO_DISPLAY_PIXEL_OF_BLOC 6, 7

BLOC_DISPLAY_ROUTINES_PIX56    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 0
BLOC_DISPLAY_ROUTINES_PIX57    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 1
BLOC_DISPLAY_ROUTINES_PIX58    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 2
BLOC_DISPLAY_ROUTINES_PIX59    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 3
BLOC_DISPLAY_ROUTINES_PIX60    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 4
BLOC_DISPLAY_ROUTINES_PIX61    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 5
BLOC_DISPLAY_ROUTINES_PIX62    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 6
BLOC_DISPLAY_ROUTINES_PIX63    MACRO_DISPLAY_PIXEL_OF_BLOC 7, 7


/**
 * Table of pixel mask
 * A and select the right pixel
 */
PIXEL_MASK
    db %10001000
    db %01000100
    db %00100010
    db %00010001


