 db '                          Brainstorm and Benediction' : db "\r\n"
 db '                                    present' : db "\r\n"
 db "\r\n"
 db '        __________.____    ________  _________    ____ ___  _________._.' : db "\r\n"
 db '        \______   \    |   \_____  \ \_   ___ \  |    |   \/   _____/| |' : db "\r\n"
 db '         |    |  _/    |    /   |   \/    \  \/  |    |   /\_____  \ | |' : db "\r\n"
 db '         |    |   \    |___/    |    \     \____ |    |  / /        \ \|' : db "\r\n"
 db '         |______  /_______ \_______  /\______  / |______/ /_______  / __' : db "\r\n"
 db '                \/        \/       \/        \/                   \/  \/' : db "\r\n"
 db ' ' : db "\r\n"
 db '                                       at' : db "\r\n"
 db '                                EVOKE      2011' : db "\r\n"
 db ' ' : db "\r\n"
 db '                Even interesting CPC demos can be done in one month' : db "\r\n\r\n"
 db 'SOUND                                                       YM PLAYER' : db "\r\n"
 db '    Ultrasyd/Brainstorm                                           Hicks/Vanity' : db "\r\n"
 db 'VISUAL                                                      DISC ROUTINES' : db "\r\n"
 db '    Voxfreax/Benediction                                         Targhan/Arkos' : db "\r\n"
 db 'CODE and BAD FAITH' : db "\r\n"
 db '    Krusty/Benediction' : db "\r\n\r\n"
  db "\r\n"
 db '                  Special thanks to Syx for his png2cpc tool' : db "\r\n"
